---

- name: Create MySQL database dump on source host - {{ src }}
  hosts: "{{ src }}"
  vars:
    src_host_backup: "{{ backup_dir }}latest.sql"
  tasks:
    - name: Test mysql dump
      command: mysqldump -u{{ db_user }} -p{{ db_pwd }} --add-drop-table --databases {{ db_name }} --result-file={{ src_host_backup }}
      tags:
        - sql-sync
        - sql-dump


- name: Transfert database dump to host {{ instance.name }}
  hosts: app
  vars:
    src_host: "{{ src }}"
    dest_host: "{{ dest }}"
    dest_host_type: "{{ hostvars[dest_host]['ansible_host'] }}"
  tasks:
    - name: Fetch file from src to dest
      fetch:
        src: "{{ hostvars[src_host]['backup_dir'] }}latest.sql"
        dest: "{{ hostvars[dest_host]['backup_dir'] }}"
        flat: true
      when: hostvars[dest_host]['ansible_host'] == 'localhost' and hostvars[src_host]['ansible_host'] != 'localhost'
      tags:
        - sql-sync
        - sql-copy


    - name: Fetch file from src to dest
      copy:
        src: "{{ hostvars[src_host]['backup_dir'] }}latest.sql"
        dest: "{{ hostvars[dest_host]['backup_dir'] }}"
      when: hostvars[dest_host]['ansible_host'] != 'localhost' and hostvars[src_host]['ansible_host'] == 'localhost'
      tags:
        - sql-sync
        - sql-copy