---

- name: "Sql Sync // Set default target for sync if not defined"
  set_fact:
     target: 'dev'
     when: target is undefined


  #Check if there is a recent dump
- name: "Sql Sync // Check if a archive exist"
  find:
    paths: "{{ hostvars[source]['backup_dir'] }}"
    age: "-3600"
    patterns: "latest-*.{{ source_db_backup_format }}"
    age_stamp: atime
  register: early_dump
  when: not host_is_target

- debug:
    var: early_dump
    verbosity: 2

- name: Sql Sync // Create MySQL database dump on source host - {{ src }}
  block:
    - command: mysqldump -u{{ db_user }} -p{{ db_pwd }} --add-drop-table --databases {{ db_name }} --result-file={{ source_db_backup }}

    - archive:
        path: "{{ source_db_backup }}"
        dest: "{{ source_db_backup }}.{{ source_db_backup_format }}"
        format: "{{ source_db_backup_format }}"

    - file:
        path: "{{ source_db_backup }}"
        state: absent
  when:
    - not host_is_target
    - early_dump.matched < 1
  tags:
    - sql-sync
    - sql-dump