#image: alpine:3.6

pipelines:
  branches:
    yalla:
      - step:
          script:
            - echo "Make git archive for commit ${BITBUCKET_COMMIT}"
            - git archive --format=tar.gz -o deploy.tgz $BITBUCKET_COMMIT
            - scp deploy.tgz deploy@37.187.57.175:/home/webdev/yalla/site/dl/
