#image: alpine:3.6

pipelines:
  branches:
    yalla:
      - step:
          name: Build archive
          script:
            - echo "Make git archive for commit ${BITBUCKET_COMMIT}"
            - git archive --format=tar.gz -o deploy.tgz $BITBUCKET_COMMIT
            - version=`git diff HEAD^..HEAD -- "$(git rev-parse --show-toplevel)"/src/cli/yalla | grep '^\+.*YALLA_VERSION' | sed -E 's/[^0-9\.]//g'` | echo $version
            - version=`git diff HEAD^..HEAD -- "$(git rev-parse --show-toplevel)"/src/cli/yalla | grep '^\+.*YALLA_VERSION' | sed -s 's/[^0-9\.]//g'` | echo $version
            - echo "Transfert archive"
            - scp deploy.tgz deploy@37.187.57.175:/home/webdev/yalla/site/dl/
