#image: alpine:3.6

pipelines:
  default:
    - step:
        name: Build archive
        script:
          - export BITBUCKET_COMMIT=$BITBUCKET_COMMIT
          - ./ci/bitbucket-deploy.sh
  custom:
    testci:
      - step:
          name: Build archive
          script:
            - export BITBUCKET_COMMIT=$BITBUCKET_COMMIT
            - ./ci/bitbucket-deploy.sh
    yalla:
      - step:
          name: Build archive
          script:
            - export BITBUCKET_COMMIT=$BITBUCKET_COMMIT
            - ./ci/bitbucket-deploy.sh
