#image: tennox/rsync-ssh-git

pipelines:
  default:
    - step:
        name: Build archive
        script:
          - export BITBUCKET_COMMIT=$BITBUCKET_COMMIT
          - ./ci/bitbucket-deploy.sh
  tags:
    v*:
      - step:
          name: Build archive
          script:
            - echo $BITBUCKET_TAG
            - git push ssh://webdev@37.187.57.175:/home/webdev/yalla/deploy.git $BITBUCKET_TAG
