#!/bin/bash

#
#
# @authors Mathias Gorenflot (mathias.gorenflot@fabernovel.com)
# @date    2017-08-29 19:20:36
# @version $Id$
#

# Exit immediately on error
set -e
trap 'echo "Aborting due to errexit on line $LINENO. Exit code: $?" >&2' ERR

##
## This script creates the necessary directories and files
## for fabernovel code projects
##

# Load common vars and functions
. "$(pwd)/yalla/src/lib/common.sh"


if ! [ -x "$(command -v yalla)" ]; then
    _install_yalla_bin
fi


_h1 "Check yalla scripts update"
_yalla_check_update

FOLDERS=(application shared logs tests)

for folder in "${FOLDERS[@]}"
do
    mkdir -p $folder;
    touch $folder/.gitkeep
done

_success "Create directories and add .gitkeep \n"

for file in ./yalla/samples/{*,.*}
do
    filename=$(basename $file)

    if [ -f "${file}" ] && [ "$filename" != "README.md" ]
        then
          if [ "$filename" == ".devilbox-run-time-settings" ]
            then
              cp $file ./.env
              _success "Copy sample file ${filename} into .env"
          else
              cp $file ./
              _success "Copy sample file ${filename}"
          fi
    fi
done

_br

_info "Create base .gitignore in project directory"

CONTENT=$(cat <<HEREDOC
# Created by the yalla create-project script

# Local yalla folder
/yalla/

# Local env files
/shared/*.local
/shared/*.local.*
/shared/local.*

# End of yalla create-project script

HEREDOC
)
printf "${CONTENT}" > .gitignore

# Common .gitignore
_gi linux,osx,windows,PhpStorm,SublimeText,VisualStudio >> .gitignore

_br

_info "Create base .gitignore in application directory"

_gi node >> "${APPLICATION_PATH_NAME}/.gitignore"

_success ".gitignore was generated with os, editor an project config"

# Setting up app and environnements settings

_yalla_settings

# Init git rempository

