#!/bin/bash

# Exit immediately on error
set -e
trap 'echo "Aborting due to errexit on line $LINENO. Exit code: $?" >&2' ERR

##
## This script creates the necessary directories and files
## for fabernovel code projects
##

# Load common vars and functions
. "$(pwd)/yalla/src/lib/common.sh"


if ! [ -x "$(command -v yalla)" ]; then
    _install_yalla_bin
fi


_h1 "Check yalla scripts update"
_yalla_check_update

# if [ "$local_version" -lt "$remote_version" ]
#   then
#     echo "version mismatch"
#   else
#     echo "qsdqs"
# fi
exit
#_line
#_h1 "Init new yalla project"


for folder in "${FOLDERS[@]}"
do
    mkdir -p $folder;
    touch $folder/.gitkeep
done

_success "Create directories and add .gitkeep \n"

for file in ./yalla/samples/{*,.*}
do
    filename=$(basename $file)

    if [ -f "${file}" ] && [ "$filename" != "README.md" ]
        then
            cp $file ./
            _success "Copy sample file ${filename}"
    fi
done

printf "\n"
_info "Create base .gitignore"
_gi linux,osx,windows,PhpStorm,SublimeText,VisualStudio > .gitignore

cat <<HEREDOC

Yalla is now installed

Usage:
  ${_ME} [--options] [<arguments>]
  ${_ME} -h | --help
Options:
  -h --help  Display this help information.
HEREDOC

_yalla_settings
