#!/usr/bin/env bash

#
#
# @authors Mathias Gorenflot (mathias.gorenflot@fabernovel.com)
# @date    2017-08-30 21:22:02
# @version $Id$
# @package yalla
#

###############################################################################
# Exit immediately on error
set -e
trap 'echo "Aborting due to errexit on line $LINENO. File $(cd $(dirname "$0"); pwd)/$(basename "$0"). Exit code: $?" >&2' ERR


###############################################################################
##
## Set paths
##

# Path variable
# From /usr/local/bin/yalla

set -o allexport
readonly APP_PATH=$WORKING_DIR

# Set paths
readonly APP_YALLA_PATH="${WORKING_DIR}/yalla"
readonly APP_YALLA_SRC="${APP_YALLA_PATH}/src"
readonly APP_YALLA_LIB="${APP_YALLA_PATH}/src/lib"
readonly APP_YALLA_ACTIONS="${APP_YALLA_PATH}/src/actions"
readonly APP_YALLA_PLUGINS="${APP_YALLA_PATH}/src/plugins"

readonly BACKUP_PATH="backup"
readonly LOCAL_BACKUP_PATH="${WORKING_DIR}/${BACKUP_PATH}"


readonly LOCAL_DOCKER_DB_HOST="127.0.0.1"

### Current user mail
USER_EMAIL=$(git config user.email)
if [ -z "${USER_EMAIL}" ]; then USER_EMAIL="admin@local.host"; fi
export USER_EMAIL

###############################################################################
##
## This file dispatch yalla command
##

. "${HOME}/.devilbox"
if [ -f "${WORKING_DIR}/yalla.settings" ]; then
    . "${WORKING_DIR}/yalla.settings"
fi

. "${APP_YALLA_LIB}/common.sh"
. "${APP_YALLA_ACTIONS}/ansible"
. "${APP_YALLA_ACTIONS}/mysql"

set +o allexport

# Die if it's not a yalla project

# Script to run
readonly action=$1
shift
#
# To preserve the original arguments,
# the _arg_list function converts the array to a string.
# Now you convert the string to a table
#

# If there is at least one parameter
if [ -n "${1}" ]; then
  IFS=$'\n'; ARGS=($(echo "${@}" | grep -E -o '"[^"]*"|\S+'))
else
  ARGS="-h"
fi

# Run Specific wrapper for
# Mysql, devilbox (docker), ansible or yalla (app) actions
case "$action" in
    project)
        case "${ARGS}" in
            init )
                _yalla_init_project
            ;;
            install )
                _yalla_install_project
            ;;
            *)
                yalla -h
                _error "${ARGS} is not a registered command"
            ;;
        esac
    ;;
    docker | dr)
        "${APP_YALLA_ACTIONS}/devilbox" "${ARGS[@]}"
    ;;
    db | mysql)
        _mysql "${@}"
    ;;
    ap | ansible-playbook)
        _ansible_playbook "${ARGS[@]}"
    ;;
    av | ansible-vault)
        _ansible_vault "${ARGS[@]}"
    ;;
    update )
        cd ./yalla && git pull origin yalla && cd $WORKING_DIR
    ;;
esac
