#!/usr/bin/env bash

# Load project settings
set -o allexport
. "${SRC}/project-configuration"
set +o allexport

# Load common vars and functions
. "${SRC}/src/lib/common.sh"

# Set current script path from app type
PLUGIN_SCRIPT_PATH="${SRC}/src/${APP_TYPE}"

# This script allow to run current project actions without specify
# current script path.
# Just set below app type (drupal8,drupal7,symfony,wordpress):

if [ ! -d "${PLUGIN_SCRIPT_PATH}" ]
    then
        _bad_exit "${APP_TYPE} does not exist. Please set an available value in project-configuration : drupal8,drupal7,symfony,wordpress";
fi

# Set Action/Script to run
ACTION=$1

# remove first args and store others
shift
ARGS=$@

# Run actions
if [ ! -f "${PLUGIN_SCRIPT_PATH}/${ACTION}.sh" ]
    then
        _bad_exit "${PLUGIN_SCRIPT_PATH}/${ACTION} does not exist.";
    else
        sh "${PLUGIN_SCRIPT_PATH}/${ACTION}.sh" $ARGS
fi
