#!/usr/bin/env bash

# Exit immediately on error
set -e
trap 'echo "Aborting due to errexit on line $LINENO. file $(cd $(dirname "$0"); pwd)/$(basename "$0"). Exit code: $?" >&2' ERR


# Load params & export local configuration
set -o allexport

CWD="/shared/httpd"
CURRENT_DIR_NAME=${PWD##*/}
CURRENT_DIR_PATH=${PWD}


# Docker shortcuts
readonly compose_file="${DEVILBOX_LOCAL_PATH}/docker-compose.yml"
readonly docker_cmd="docker-compose -f ${compose_file}"
readonly docker_exec="${docker_cmd} exec --user devilbox php env TERM=xterm /bin/sh -c"
readonly docker_mysql_cmd="${docker_cmd} exec --user devilbox php env mysql -h 127.0.0.1 -u root"

set +o allexport

readonly DV_ACTION=$1
shift

case "$DV_ACTION" in
    config | stop | build | start )
        $docker_cmd "$DV_ACTION"
        ;;
    up)
        $docker_cmd up -d $DOCKER_STACK
        ;;
    cleanup)
        $docker_cmd rm -f
        ;;
    ssh)
        $docker_exec "cd ${CWD}; exec bash -l"
        ;;
    connect)
        $docker_exec "cd ${CWD}/${CURRENT_DIR_NAME}; exec bash -l"
        ;;
    exec)
        #shift
        $docker_exec "cd ${CWD}/${CURRENT_DIR_NAME}; $(_args_list "$@")"
        ;;
    # ------ unsed
    # code)
    #     shift
    #     $docker_exec "cd ${CWD}/${CURRENT_DIR_NAME}/; ./code $(_args_list "$@")"
    #     ;;
    # There is a bug with docker compose and pipe, tty, ..
    # so I use a script to execute a script on the docker container
    # @see https://github.com/docker/compose/issues/3352
    # ------ / unsed
    # ----- Really necessary ?
    # install)
    #     _info "Start docker stack"
    #     $docker_cmd up -d $DOCKER_STACK;

    #     _info "\nCreate database or import an existing file"
    #     _mysql_install_actions


    #     _info "Install project"
    #     $docker_exec "cd ${CWD}/${CURRENT_DIR_NAME}/; ./code install";
    #     ;;
    # ------ / really
    shortlist)
            echo config up stop cleanup exec code ssh shortlist
        ;;
    *)
        echo "${DV_ACTION} is not a registered command"
        echo "config up stop cleanup ssh are available command"
        exit 1
esac

