#!/usr/bin/env bash

# Exit immediately on error
set -e
trap 'echo "Aborting due to errexit on line $LINENO. file $(cd $(dirname "$0"); pwd)/$(basename "$0"). Exit code: $?" >&2' ERR

readonly DV_ACTION=$1
shift

usage() {
cat << EOF

Usage : yalla dr [options]

Options
----------------------------------------------------------------------
  config             Validate and view the Compose file
  stop               Stop services
  start              Start local docker stack
  up                 Start a specific container
  build              Build or rebuild services
  cleanup [ -v]      Remove stopped containers without asking to confirm removal.
                     < -v > Remove any anonymous volumes attached to containers
  ssh                Connect to main docker container, where the code is and where the commands are available (wp cli, node, ...)
  connect            Connect to main docker container, directly in path to project
  exec               Execute a command in a running container
  restart            Stop and restart container with cleanup

EOF
}

case "$DV_ACTION" in
    config | stop | build )
        $docker_cmd "$DV_ACTION"
        ;;
    start )
        $docker_cmd up -d $DOCKER_STACK
        ;;
    up )
        $docker_cmd up -d "${@}"
        ;;
    restart)
        $docker_cmd stop && $docker_cmd rm -f && $docker_cmd up -d $DOCKER_STACK
        ;;
    cleanup)
        $docker_cmd stop
        if [ $# -eq 1 ] && [ "${1}" == "-v" ]; then
            $docker_cmd rm -v
        else
            $docker_cmd rm -f
        fi
        ;;
    ssh)
        $docker_exec "cd ${CWD}; exec bash -l"
        ;;
    connect)
        $docker_exec "cd ${CWD}/${CURRENT_DIR_NAME}; exec bash -l"
        ;;
    exec)
        #shift
        $docker_exec "cd ${CWD}/${CURRENT_DIR_NAME}; $(_args_list "$@")"
        ;;
    # ------ unsed
    # code)
    #     shift
    #     $docker_exec "cd ${CWD}/${CURRENT_DIR_NAME}/; ./code $(_args_list "$@")"
    #     ;;
    # There is a bug with docker compose and pipe, tty, ..
    # so I use a script to execute a script on the docker container
    # @see https://github.com/docker/compose/issues/3352
    # ------ / unsed
    # ----- Really necessary ?
    # install)
    #     _info "Start docker stack"
    #     $docker_cmd up -d $DOCKER_STACK;

    #     _info "\nCreate database or import an existing file"
    #     _mysql_install_actions


    #     _info "Install project"
    #     $docker_exec "cd ${CWD}/${CURRENT_DIR_NAME}/; ./code install";
    #     ;;
    # ------ / really
    shortlist )
            echo '
      config
      stop
      start
      up
      build
      cleanup
      ssh
      connect
      exec
      restart
        '
        ;;
    -h | --help )
          usage
        ;;
    *)
        usage
        _br
        _error "${DV_ACTION} is not a registered command"
        exit 1
esac
