#!/usr/bin/env bash

# Exit immediately on error
set -e
trap 'echo "Aborting due to errexit on line $LINENO. file $(cd $(dirname "$0"); pwd)/$(basename "$0"). Exit code: $?" >&2' ERR


# [ ! "$(docker ps -a | grep <name>)" ]

_usage() {
    echo '
Examples :
    yalla db | mysql -d database_name -f path/to/file.sql : import a database
    yalla db | mysql -d database_name -i "SHOW TABLES;" : run an inline sql command script
    yalla db | mysql -i "SHOW DATABASES;" : run an inline sql command script
    yalla db | mysql -f ./backup/create_user_and_database.sql : import an sql file
'
_info 'With option -f, the mysql file must be somewhere in the current project'
_br
}

function _mysql() {
    local args=("$@")
    local INLINE=
    local DATABASE=""
    local FILE=""

    local optspec="i:d:f:h"

    while getopts "$optspec" opt "${args[@]}"; do
        case "${opt}" in
            i )
                INLINE="${OPTARG}"
                ;;
            d )
                DATABASE="${OPTARG}"
                ;;
            f )
                FILE="${OPTARG}"
                ;;
            h )
                _usage
                ;;
            \?)
                _notice "Bad use or missing arguments."
                echo "Invalid option: -$OPTARG" >&2
                _usage
            ;;
        esac
    done

    # Import a sql file
    if [[ ! -z $FILE ]]; then
        if [ ! -e "${FILE}" ]; then
            _bad_exit "No ${FILE} file was found in the directory";
        fi
        _info "Run : mysql -u root -h ${LOCAL_DOCKER_DB_HOST} ${DATABASE} < ${CWD}/${CURRENT_DIR_NAME}/${FILE};"
        docker-compose -f "${DEVILBOX_LOCAL_PATH}/docker-compose.yml" exec --user devilbox php env TERM=xterm /bin/sh -c "mysql -u root -h ${LOCAL_DOCKER_DB_HOST} ${DATABASE} < ${CWD}/${CURRENT_DIR_NAME}/${FILE};"
    fi

    # Run inline mysql command
    if [[ ! -z $INLINE ]]; then
        # I don't know why, but $docker_exec generate an error.
        _info "Run : echo \"${INLINE}\" | mysql -u root -h ${LOCAL_DOCKER_DB_HOST} ${DATABASE}"
        docker-compose -f "${DEVILBOX_LOCAL_PATH}/docker-compose.yml" exec --user devilbox php env TERM=xterm /bin/sh -c "echo \"${INLINE}\" | mysql -u root -h ${LOCAL_DOCKER_DB_HOST} ${DATABASE}"
    fi
}
