#!/usr/bin/env bash

# Exit immediately on error
set -o nounset
set -o errexit
set -o pipefail
IFS=$'\n\t'
trap 'echo "Aborting due to errexit on line $LINENO. Exit code: $?" >&2' ERR

YALLA_VERSION=0.1.2

. "${HOME}/.yalla.autocomplete"

# Preserve original arguments with quotes
# @see : https://stackoverflow.com/questions/3755772/how-to-preserve-double-quotes-in-in-a-shell-script/26733366#26733366
_args_list(){
    argList=""
    #iterate on each argument
    for arg in "$@"
    do
      #if an argument contains a white space, enclose it in double quotes and append to the list
      #otherwise simply append the argument to the list
      if echo $arg | grep -q " "; then
       argList="$argList \"$arg\""
      else
       argList="$argList $arg"
      fi
    done

    #remove a possible trailing space at the beginning of the list
    argList=$(echo $argList | sed 's/^ *//')

    echo "$argList"
}

declare -x -f _args_list;

## Set Variables

export WORKING_DIR=$(pwd)

## Exit if not args or not a yalla project
# if [ ! -d "./yalla" ] && [ "$1" != "create-project" ]; then
#     cat <<HEREDOC
#     The "yalla" directory does not appear to be present.
#     Run <yalla create-project> or go to a directory where yall is installed
# HEREDOC
#     exit 1;
# fi

## Parse args
CMD=${1:--h}

if ! [ -z "$@" ]
  then
    shift
    ARGS=$@
fi

while [ $# -gt 0 ]; do
  case "$CMD" in
      create-project)
          git clone -b skeleton-rework --single-branch git@bitbucket.org:buzzaka/project-skeleton.git yalla && ./yalla/create-project
          ;;

      docker | ssh | mysql | app )
          echo "@todo $(args_list "$@")"
          ;;
      -v | --version)
          echo 'yalla version ' ${YALLA_VERSION}
          echo 'yalla path ' $(which yalla)
          ;;
      -h | --help)
          echo "@todo"
          ;;
      self-update)
          echo "@todo"
          ;;
      update)
          echo "@todo"
          ;;
    shortlist)
        cat <<HEREDOC
        create-project
        docker
        ssh
        -v, --version
        update
HEREDOC
        ;;
       *)
          echo "${CMD} is not a registered command"
          exit 1
  esac
  shift
done
