# roles/mysql-sync/tasks/transfert-database.yml
---

- stat:
    path: "{{ source_db_backup_archive }}"
  register: dumpfile
  when: not host_is_target

- name: Fetch dump from {{ source }} to {{ target }}
  block:
    # When source is not localhost
    - fetch:
        src: "{{ source_db_backup_archive }}"
        dest: "{{ hostvars[target]['backup_dir'] }}"
        flat: true
      when: dest_host_type == 'localhost'

    # When source is localhost
    - copy:
        src: "{{ source_db_backup_archive }}"
        dest: "{{ hostvars[target]['backup_dir'] }}"
      when: dest_host_type != 'localhost'

  when: (dumpfile.stat is defined and dumpfile.stat.readable)
  tags:
    - sql-sync
    - sql-copy