---

# To use this playbook,  NO ansible mysql modules are required.
# If failed, please run dependencies playbook
#
# Command :
#   ansible-playbook mysql-sync.yml -e "source=staging" --ask-vault-pass
#   ansible-playbook mysql-sync.yml -e "source=staging target=preprod" --ask-vault-pass

- name: Sync databases

  vars:
    # Target is an optional args. Set default value if not defined
    var_target: "{{ target | default('dev') }}"
    # Shortcuts
    host_is_target: "{{ (inventory_hostname == hostvars[target]['inventory_hostname_short']) }}"
    dest_host_type: "{{ hostvars[target]['ansible_host'] }}"
    # dump file
    source_db_backup: "{{ hostvars[source]['backup_dir'] }}latest-{{ hostvars[source]['inventory_hostname_short'] }}.sql"
    source_db_backup_format: bz2
    source_db_backup_archive: "{{ source_db_backup }}.{{ source_db_backup_format }}"

  vars_files:
    - /ansible-config/vaults/vault.yml

  hosts: "{{ source }},{{ var_target }}"
  gather_facts: true
  roles:
    - mysql-sync
    - mysql-transfert-database
  tags:
    - sql
    - sql-sync
