---

# To use this playbook, ansible mysql modules must installed.
# If failed, please run dependencies playbook

- name: Sync databases
  vars_files:
    - ./group_vars/vault.yml
  vars:
    # Target is an optional args. Set default value if not defined
    var_target: "{{ target | default('dev') }}"
  hosts: "{{ source }},{{ var_target }}"
  gather_facts: true
  roles:
    - role: mysql-sync-ansible
  tags:
    - sql
    - sql-sync
