---

# - name: Test privilege escalation
#   hosts: staging
#   gather_facts: false
#   become: true
#   become_user: "{{ hostvars[inventory_hostname]['become_user'] }}"
#   #become_method: "{{ hostvars[inventory_hostname]['become_method'] }}"
#   roles:
#     - tests


- name: Install Ansible requirements

  vars_files:
    - ./group_vars/vault.yml

  hosts: app
  gather_facts: true
  become: true
  roles:
    - role: common
  tags:
    - common

- name: Sync databases

  vars_files:
    - ./group_vars/vault.yml

  hosts:
    - dev
    - staging
  vars:
    source: "{{ source }}"
    target: "{{ target }}"
  gather_facts: true
  roles:
    - role: mysql-sync-ansible
  tags:
    - sql
    - sql-sync
